name: .venv
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2024.3.11=hca03da5_0
  - libffi=3.4.4=hca03da5_1
  - ncurses=6.4=h313beb8_0
  - openssl=3.0.13=h1a28f6b_1
  - pip=24.0=py311hca03da5_0
  - python=3.11.7=hb885b13_0
  - readline=8.2=h1a28f6b_0
  - setuptools=69.5.1=py311hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - tk=8.6.14=h6ba3021_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.43.0=py311hca03da5_0
  - xz=5.4.6=h80987f9_1
  - zlib=1.2.13=h18a0788_1
  - pip:
      - black==24.4.2
      - click==8.1.7
      - mypy-extensions==1.0.0
      - packaging==24.0
      - pathspec==0.12.1
      - platformdirs==4.2.1
prefix: /opt/anaconda3/envs/.venv
