name: algoriths-and-data-structures
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2024.7.2=hca03da5_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - libffi=3.4.4=hca03da5_1
  - ncurses=6.4=h313beb8_0
  - openssl=3.0.14=h80987f9_0
  - packaging=24.1=py311hca03da5_0
  - pip=24.0=py311hca03da5_0
  - pluggy=1.0.0=py311hca03da5_1
  - py=1.11.0=pyhd3eb1b0_0
  - pytest=7.4.4=py311hca03da5_0
  - pytest-html=3.1.1=pyhd3eb1b0_1
  - pytest-metadata=3.0.0=py311hca03da5_0
  - python=3.11.7=hb885b13_0
  - readline=8.2=h1a28f6b_0
  - setuptools=72.1.0=py311hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - tk=8.6.14=h6ba3021_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.43.0=py311hca03da5_0
  - xz=5.4.6=h80987f9_1
  - zlib=1.2.13=h18a0788_1
prefix: /opt/anaconda3/envs/algoriths-and-data-structures
